### ISSUE TITLE
Test error trace is displayed even if the tests are passed successfully

### ISSUE THREAD

**Issue by florinbardosi** [jintoppy/protractor-html-screenshot-reporter#55]
After tests run, in JSON response file an error trace is displayed, even if the tests are passed.

[{"description":"should have a title|The main view","passed":true,"os":"WIN8_1","browser":
{"name":"chrome","version":"42.0.2311.135"},
"message":"Passed.",
"trace":"Error: Failed expectation\n    
at [object Object].<anonymous> (...workspace\\e2e\\main.spec.js:12:36)\n    
at ...workspace\\node_modules\\protractor\\node_modules\\jasminewd\\index.js:94:14\n    
at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (...workspace\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:1654:20)\n    
at [object Object].webdriver.promise.ControlFlow.runEventLoop_ (...workspace\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:1518:8)\n    
at [object Object].wrapper [as _onTimeout] (timers.js:265:14)\n    
at Timer.listOnTimeout (timers.js:110:15)",
"screenShotFile":"chrome\\should have a title-The main view.png"},

**Comment by majdamarcin** [comment]
I got almost the same results in json files (note: this is not displayed on console screen):
```javascript
"Error: Failed expectation\n
at [object Object].<anonymous>(C:\\xampp\\htdocs\\ttr\\_htrr\\tests\\e2e\\specs\\conditions.js:17:41)\n
at C:\\xampp\\htdocs\\ttr\\node_modules\\protractor\\node_modules\\jasminewd\\index.js:94:14\n
at [object Object].promise.ControlFlow.runInFrame_
(C:\\xampp\\htdocs\\ttr\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:1877:20)\n
at [object Object].promise.ControlFlow.runEventLoop_ (C:\\xampp\\htdocs\\ttr\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:1755:8)\n
at [object Object].<anonymous> (C:\\xampp\\htdocs\\ttr\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\webdriver\\promise.js:2056:12)\n
at [object Object].goog.async.run.processWorkQueue [as _onTimeout] (C:\\xampp\\htdocs\\ttr\\node_modules\\protractor\\node_modules\\selenium-webdriver\\lib\\goog\\async\\run.js:125:21)\n
at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)","
```
Test passed, but trace isn't empty.
My packages:
```javascript
"devDependencies": {
    "chromedriver": "~2.8.0",
    "grunt": "~0.4.2",
    "grunt-contrib-clean": "~0.4.1",
    "grunt-contrib-compass": "~0.2.0",
    "grunt-contrib-concat": "~0.1.3",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-jshint": "~0.3.0",
    "grunt-contrib-uglify": "~0.2.0",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-contrib-yuidoc": "~0.4.0",
    "grunt-css": "~0.5.4",
    "grunt-ddescribe-iit": "0.0.6",
    "grunt-html2js": "~0.2.4",
    "grunt-hub": "~0.6.0",
    "grunt-karma": "~0.8.3",
    "grunt-protractor-runner": "^2.0.0",
    "grunt-remove-logging": "~0.1.1",
    "grunt-replace": "~0.4.2",
    "grunt-sass": "~0.4.0",
    "grunt-selenium-simple": "~0.1.1",
    "install": "^0.1.8",
    "jasmine-core": "^2.2.0",
    "jasmine-spec-reporter": "^1.1.2",
    "karma": "~0.12.19",
    "karma-chrome-launcher": "~0.1.4",
    "karma-firefox-launcher": "~0.1.3",
    "karma-html-reporter": "^0.2.6",
    "karma-jasmine": "^0.3.5",
    "karma-phantomjs-launcher": "~0.1.4",
    "karma-safari-launcher": "~0.1",
    "karma-verbose-reporter": "0.0.1",
    "npm": "^2.6.1",
    "phantomjs": "~1.9.7",
    "protractor": "^2.0.0",
    "protractor-html-screenshot-reporter": "0.0.19",
    "selenium": "~2.20.0"
  }
```

**Comment by pilootchoum** [comment]
Got the same bug;
